### ISSUE TITLE
Arquivos misturam comandos para acentuação e caracteres acentuados.

### ISSUE THREAD

**Issue by cako** [lpoo/modelo_tese_imecc#10]
Quase todos os arquivos da têm tanto comandos `\~{a}` como letras tipo `ã`. Deveríamos padronizar isso. Eu tenho um programa que converte os arquivos de um tipo para o outro de forma bem rápida e posso fazer isso em um commit. Mas queria primeiro esperar que entrassem os outros commits.

Além disso queria propor que o default fosse com os caracteres nativos. Colocaríamos de forma bem evidente na documentação que se as letras não aparecem é que o usuário deve mudar de editor e/ou compilador.
Se não concordarem, não tem problema, deixamos tudo em comandos. O que importa é a consistência!

**Comment by cako** [comment]
O programinha do qual estou falando se encontra aqui: https://github.com/cako/latin2utf8

**Comment by rgaiacs** [comment]
AFAIK, o Plamen tinha pedido para deixar em ASCII e acredito que essa seja a melhor opção.

Ficaria feliz se pudesse aplicar seu script para remover algum caractere Latin-1 que tenha ficado perdido.

**Comment by cako** [comment]
d66884c91fcb7afc12e80408636f29700264f666, d92650035e6c3cc8ee3d38eaac959f594756676f
