### ISSUE TITLE
Logo da UNICAMP como PDF

### ISSUE THREAD

**Issue by rgaiacs** [lpoo/modelo_tese_imecc#17]
Migrar o logo da capa para PDF.

**Comment by cako** [comment]
Eu tenho um logo em PDF que usei para a minha tese ([aqui](http://ge.tt/1TydCFc/v/0?c)). Modéstia parte ele está bastante bom! Eu criei ele utilizando o [EPS disponível no site](http://www.unicamp.br/unicamp/sites/default/files/logotipo/PRE_VERM.EPS) e convertendo pra PDF.

Outra forma seria utilizar as [instruções na página da Unicamp](http://www.unicamp.br/unicamp/a-unicamp/logotipo/codigo-de-identidade-visual) para criar um código em TikZ ou algo pelo estilo. As instruções são completamente detalhadas e dariam um ótimo exercício em TikZ, mas acho overkill!

**Comment by rgaiacs** [comment]
Depois do feriado eu vou pegar esse seu PDF e fazer a substituição.

Embora as instruções no site deixem muito fácil recriar o logo no TikZ não vou fazer isso no momento por questão da fonte do nome UNICAMP.
