### ISSUE TITLE
Inserir texto sobre uma imagem

### ISSUE THREAD

**Issue by rgaiacs** [lpoo/modelo_tese_imecc#18]
Adicionar pacote e exemplo de texto sobre uma imagem.

**Comment by cako** [comment]
A discussão no StackOverflow se encontra aqui: http://tex.stackexchange.com/questions/9559/drawing-on-an-image-with-tikz

O pacote se encontra aqui: http://bazaar.launchpad.net/~tex-sx/tex-sx/development/view/head:/onimage.dtx
Para instalá-lo, rodar `pdflatex onimage.dtx`. Para fins do modelo de tese, isto deve ser rodado uma vez somente, para gerar o .sty, e este é o arquivo que deve ser incluso no modelo. Opcionalmente, também podemos fornecer o manual em pdf que também é gerado.

**Comment by rgaiacs** [comment]
Eu tinha olhada essa pergunta mas passei batido no comentário. Me parece que o `onimage` ainda não foi adicionado ao CTAN e por isso acredito que seja prudente não adicioná-lo no momento.

De qualquer maneira, quando tiver um tempo depois do feriado vou adicionar algum exemplo baseado nas respostas presentes na discussão.
