### ISSUE TITLE
Warning: Font shape `T1/lmr/bx/sc' undefined

### ISSUE THREAD

**Issue by rgaiacs** [lpoo/modelo_tese_imecc#20]
Esse warning foi notificado pelo Tiago Macedo tiago.rmacedo@gmail.com e ocorre na capa do modelo e por causa dele o título do trabalho não fica em caixa auta como "deveria".

**Comment by cako** [comment]
Este warning ocorre pelo fato de que um tipo de fonte não foi achado. No caso a fonte é a Latin Modern (lmr) very bold (bx), small caps (sc).

Uma solução é a detalhada aqui: http://tex.stackexchange.com/questions/22240/choosing-font-for-bold-small-caps-or-any-other-particular-familyseriesshape-c

Será comitada em breve.
